#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N QC_Trim
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=40GB,ncpus=5
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Create paths to required software or load modules"
module load fastqc/0.11.7
module load parallel/20191022 
module load multiqc/1.9 
module load python3/3.8.5
export PATH=$PATH:/g/data/pq84/bin/TrimGalore-0.6.6/ # trim galore wrapper for fastq and cutadapt
export PATH=$PATH:/home/588/jw1542/.local/bin # cutadapt_3.5 installed here

echo "---------------------------------------"
echo "Set environment variable"
QC_OUTDIR="/g/data/pq84/malaria/Pm/outputs/01_QC_Trim"
mkdir $QC_OUTDIR

echo "---------------------------------------"
echo "QC"
cd /g/data/pq84/malaria/Pm/data/kaust/Menzies
fastqc -t 5 -o $QC_OUTDIR *.fastq.gz
multiqc $QC_OUTDIR/. -o $QC_OUTDIR

echo "---------------------------------------"
echo "Finished"